spec:
  template:
    spec:
      containers:
        - name: vertx
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 8082
              name: hello
              protocol: TCP
