global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
    artifact: 'vertx-micrometer-metrics'

rule_files:
  - 'prometheus.rules.yml'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['localhost:9090']
        labels:
          group: 'test'

  - job_name: 'vertx'
    scrape_interval: 5s
    static_configs:
      - targets: ['${project.artifactId}:8080']
        labels:
          group: 'vertx'
