spec:
  template:
    spec:
      containers:
        - name: vertx
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 1883
              name: mqtt
              protocol: TCP
