CREATE TABLE PERSON (
  ID   INT          NOT NULL,
  NAME VARCHAR(100) NOT NULL
);

INSERT INTO PERSON (ID, NAME) VALUES (1, 'toto');
INSERT INTO PERSON (ID, NAME) VALUES (2, 'titi');
INSERT INTO PERSON (ID, NAME) VALUES (3, 'tata');
