apiVersion: v1
kind: Service
metadata:
  name: mqtt-broker-nodeport
spec:
  ports:
  - name: mqtt-nodeport
    port: 1883
    protocol: TCP
    targetPort: 1883
  selector:
    app: mqtt-broker
    group: io.vertx.openshift
    provider: fabric8
  sessionAffinity: None
  type: NodePort
